/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClassicBoard: typeof import('./src/components/game/boards/ClassicBoard.vue')['default']
    Field: typeof import('./src/components/game/Field.vue')['default']
    PlayerPiece: typeof import('./src/components/game/PlayerPiece.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
